data:
  size: 15000
  specs:
    - name: spell_backward
      weight: 1
      config:
        min_word_len: 3
        max_word_len: 10

loss: reinforce
model_name: Qwen/Qwen3-1.7B
beta: 0.0  # KL penalty coefficient (0 = disabled, set >0 to enable)
lr: 5e-6
temperature: 0.6
top_p: 0.95
top_k: 20
min_p: 0.0
max_new_tokens: 512
prompts_per_step: 8
num_rollouts: 1  # for REINFORCE num_rollouts should be 1
rollout_batch_size: 8
train_batch_size: 2
batch_acc: 4
max_norm: 1.0
seed: 42
model_device_id: 0
wandb_project: rlhf-book
wandb_run_name: reinforce_spell_backwards
